const aulas = [

{
id:1,
titulo:"(Aula 01) Introdução ao CorelDRAW",
liberada:true,
video:"https://www.youtube.com/watch?v=Ml2exCaowPY",
slide:"2PACX-1vSRdq6Mn00dp-6CcObEK2cmB54JT6od9tzxcK4cTuYbY5pOW4tX8nJuFJ6-hMmx74If_rO6TMj3bEWB",
temSlide:true,
temArquivos:false,
arquivos:"#",
thumb:"thumbs/Aula01.jpeg",
},

{
id:2,
titulo:"(Aula 02) Tipos de Arquivos",
liberada:true,
video:"https://www.youtube.com/watch?v=WeKHEkSRvhM",
slide:"2PACX-1vQc3IQCvztL1TD1x7LCDkzEHvAsFoqHZjuloCcD9AfeDR5jRylmvKkShMXvM-PVS5de7Bwvttt7qAZb",
temSlide:true,
temArquivos:false,
arquivos:"#",
thumb:"thumbs/aula02.jpeg"
},

{
id:3,
titulo:"(Aula 03) Desenhos Vetoriais",
liberada:true,
video:"https://www.youtube.com/watch?v=uGcE4y2X0IM",
slide:"2PACX-1vSNjdAonPX2QSx72WEEP-T9RdOrXKzjgeYiRofubeleb5izF6Ecq9XylIWoYSINt7U-M0602sL5LIoy",
temSlide:true,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/1uwQaIdo3fGH5hO-RA8hI-fLy6ZCGDH10?usp=sharing",
thumb:"thumbs/Aula03.jpeg"
},

{
id:4,
titulo:"(Aula 04) Tipografia",
liberada:true,
video:"https://youtu.be/djfcSIuDo1s",
slide:"2PACX-1vR9DJ8RlXXdEciIbGp-AhQnSf8KVQjtaQkJbOX_a3J5tbVrOB2RXPUgIvY5zf0lA-9hGfmyLlEAqKWm",
temSlide:true,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/1Si3nBSIZPTj0zIITIGdlO39pACm14Owi?usp=sharing",
thumb:"thumbs/aula04.png"
},

{
id:5,
titulo:"(Aula 05) Cartão de Visitas",
liberada:true,
video:"https://youtu.be/6639CJgxJ-g",
slide:"#",
temSlide:false,
temArquivos:false,
arquivos:"#",
thumb:"thumbs/Aula05.jpg"
},

{
id:6,
titulo:"(Aula 06) Vetorização Rápida",
liberada:true,
video:"https://www.youtube.com/watch?v=uAkFXiTNQ88",
slide:"#",
temSlide:false,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/13k4u18HGGK1LbI_CFHM8gPZO3hCvBkRV?usp=drive_link",
thumb:"thumbs/Aula06.jpeg",
},

{
id:7,
titulo:"(Aula 07) Anúncio",
liberada:true,
video:"https://youtu.be/qU13nDac2zM",
slide:"#",
temSlide:false,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/19IuTxyPmIX1JzV5ZLO3LKW_BYLlmRV33?usp=sharing",
thumb:"thumbs/Aula07.png",
},
{
id:8,
titulo:"(Aula 08) Mini Revisão",
liberada:true,
video:"https://www.youtube.com/watch?v=dBzAnJy8Kbk",
slide:"#",
temSlide:false,
temArquivos:false,
arquivos:"",
thumb:"thumbs/Aula08.jpg",
},
{
id:9,
titulo:"(Aula 09) Banners",
liberada:true,
video:"https://www.youtube.com/watch?v=Z001x2BFx84",
slide:"#",
temSlide:false,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/1xcLg7rBdzTKIatMS5Ocx1IMe3gYAGnJS?usp=sharing",
thumb:"thumbs/SupraBaneer2.jpg",
},
{
id:10,
titulo:"(Aula 10) Portfólio",
liberada:true,
video:"https://youtu.be/i-ZHB7Kb1Yg",
slide:"#",
temSlide:false,
temArquivos:false,
arquivos:"",
thumb:"thumbs/aula10.jpg",
},
{
id:11,
titulo:"(Aula 11) Cardápio",
liberada:true,
video:"https://youtu.be/3qvK6ww2Tms",
slide:"#",
temSlide:false,
temArquivos:false,
arquivos:"",
thumb:"thumbs/11.png",
},
{
id:12,
titulo:"(Aula 12) Criando Elementos",
liberada:true,
video:"https://youtu.be/SwZQN8v8P_s",
slide:"#",
temSlide:false,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/1DlTd7D9PW0fmrEk3rr07N7YVpqCCqIu9?usp=sharing",
thumb:"thumbs/12.jpeg",
},

{
id:13,
titulo:"(Aula 13) Mokups",
liberada:true,
video:"https://www.youtube.com/watch?v=yOCoLciHKT4",
slide:"#",
temSlide:false,
temArquivos:true,
arquivos:"https://drive.google.com/drive/folders/1M1IpzxOB5HmzEOoQ9D3L6mohvFkBK3nC?usp=sharing",
thumb:"thumbs/aula13.JPG",
},


];
